"""Write the code font's glyph coverage for hooks/code_glyphs.py.

Reads a TrueType file's `cmap` (formats 4 and 12) and `hmtx` tables with the
standard library only, and writes the code points that map to a glyph of the
font's regular advance width — the ones a code block can use without breaking
column alignment — as compact ranges, one `start-end` per line, in hex.

Run it whenever the vendored code font changes:

    python scripts/font_coverage.py path/to/JetBrainsMono-Regular.ttf \
        docs/assets/fonts/JetBrainsMono-coverage.txt

The TTF is an input only; the site serves the WOFF2 files.
"""

import struct
import sys
from collections import Counter


def tables(data):
    num = struct.unpack(">H", data[4:6])[0]
    out = {}
    for i in range(num):
        tag, _, off, length = struct.unpack(">4sIII", data[12 + 16 * i : 28 + 16 * i])
        out[tag.decode("latin-1")] = data[off : off + length]
    return out


def cmap(tab):
    _, n = struct.unpack(">HH", tab[:4])
    subs = []
    for i in range(n):
        pid, eid, off = struct.unpack(">HHI", tab[4 + 8 * i : 12 + 8 * i])
        fmt = struct.unpack(">H", tab[off : off + 2])[0]
        subs.append((fmt, off))
    mapping = {}
    for fmt, off in sorted(subs, key=lambda s: s[0]):
        if fmt == 4:
            segx2 = struct.unpack(">H", tab[off + 6 : off + 8])[0]
            seg = segx2 // 2
            base = off + 14
            ends = struct.unpack(f">{seg}H", tab[base : base + segx2])
            starts = struct.unpack(f">{seg}H", tab[base + segx2 + 2 : base + 2 * segx2 + 2])
            deltas = struct.unpack(f">{seg}h", tab[base + 2 * segx2 + 2 : base + 3 * segx2 + 2])
            ro_pos = base + 3 * segx2 + 2
            ranges = struct.unpack(f">{seg}H", tab[ro_pos : ro_pos + segx2])
            for s in range(seg):
                for c in range(starts[s], ends[s] + 1):
                    if c == 0xFFFF:
                        continue
                    if ranges[s] == 0:
                        g = (c + deltas[s]) & 0xFFFF
                    else:
                        p = ro_pos + 2 * s + ranges[s] + 2 * (c - starts[s])
                        g = struct.unpack(">H", tab[p : p + 2])[0]
                        if g:
                            g = (g + deltas[s]) & 0xFFFF
                    if g:
                        mapping[c] = g
        elif fmt == 12:
            ngroups = struct.unpack(">I", tab[off + 12 : off + 16])[0]
            for i in range(ngroups):
                s, e, g = struct.unpack(">III", tab[off + 16 + 12 * i : off + 28 + 12 * i])
                for c in range(s, e + 1):
                    mapping[c] = g + c - s
    return mapping


def advances(t):
    nh = struct.unpack(">H", t["hhea"][34:36])[0]
    hm = t["hmtx"]
    widths = [struct.unpack(">H", hm[4 * i : 4 * i + 2])[0] for i in range(nh)]
    return lambda g: widths[g] if g < nh else widths[-1]


def ranges(cps):
    cps = sorted(cps)
    out = []
    start = prev = cps[0]
    for c in cps[1:]:
        if c != prev + 1:
            out.append((start, prev))
            start = c
        prev = c
    out.append((start, prev))
    return out


def main(src, dst):
    data = open(src, "rb").read()
    t = tables(data)
    m = cmap(t["cmap"])
    adv = advances(t)
    regular = Counter(adv(g) for c, g in m.items() if 0x20 <= c < 0x7F).most_common(1)[0][0]
    good = [c for c, g in m.items() if adv(g) == regular]
    with open(dst, "w", encoding="ascii", newline="\n") as f:
        f.write(f"# Generated by scripts/font_coverage.py from {src.replace(chr(92), '/').split('/')[-1]}\n")
        f.write(f"# Code points drawn at the regular advance width ({regular} units). Do not edit.\n")
        for a, b in ranges(good):
            f.write(f"{a:04X}-{b:04X}\n")
    print(f"{len(m)} mapped, {len(good)} at width {regular}, {len(ranges(good))} ranges -> {dst}")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
